CREATE TABLE tasks(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY
	, title VARCHAR(255) NOT NULL DEFAULT ''
	, subtitle VARCHAR(255) NOT NULL DEFAULT ''
	, start_at TIME NOT NULL
	, finish_at TIME NOT NULL
	, is_done BOOLEAN NOT NULL DEFAULT FALSE
	, created_at TIMESTAMP NOT NULL DEFAULT NOW()
	, updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);